"""add_phone_code_hash_to_ai_accounts

Revision ID: 1b46139cbac0
Revises: 5b19c2d3e4f2
Create Date: 2025-08-02 01:07:19.673159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b46139cbac0'
down_revision: Union[str, None] = '5b19c2d3e4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_accounts', sa.Column('phone_code_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_accounts', 'phone_code_hash')
    # ### end Alembic commands ###
