"""change_selected_groups_group_id_to_string

Revision ID: e9fd032ae9d5
Revises: 7e0053f0afa2
Create Date: 2025-08-02 09:03:41.420055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9fd032ae9d5'
down_revision: Union[str, None] = '7e0053f0afa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('selected_groups', 'group_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('selected_groups', 'group_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
