"""add is_monitored to groups

Revision ID: 015375dc45e9
Revises: e9fd032ae9d5
Create Date: 2025-08-05 19:02:22.731722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "015375dc45e9"
down_revision: Union[str, None] = "e9fd032ae9d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("is_monitored", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "is_monitored")
    # ### end Alembic commands ###
