"""add_cols_to_ai_accounts

Revision ID: 7873844e4109
Revises: 015375dc45e9
Create Date: 2025-08-06 02:19:01.569162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7873844e4109"
down_revision: Union[str, None] = "015375dc45e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_accounts", sa.Column("shareable_link", sa.String(), nullable=True)
    )
    op.add_column(
        "ai_accounts", sa.Column("ai_response_context", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_accounts", "ai_response_context")
    op.drop_column("ai_accounts", "shareable_link")
    # ### end Alembic commands ###
