"""add_new_cols_to_models

Revision ID: d09ddfe635c8
Revises: 7873844e4109
Create Date: 2025-09-21 18:11:44.202612

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d09ddfe635c8"
down_revision: Union[str, None] = "7873844e4109"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_attempts_id"), "login_attempts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_login_attempts_ip_address"),
        "login_attempts",
        ["ip_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_login_attempts_phone_number"),
        "login_attempts",
        ["phone_number"],
        unique=False,
    )
    op.create_table(
        "blacklisted_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("token_type", sa.String(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "blacklisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_blacklisted_tokens_id"), "blacklisted_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_blacklisted_tokens_jti"), "blacklisted_tokens", ["jti"], unique=True
    )
    op.add_column(
        "active_sessions", sa.Column("access_token_jti", sa.String(), nullable=True)
    )
    op.add_column(
        "active_sessions", sa.Column("refresh_token_jti", sa.String(), nullable=True)
    )
    op.add_column(
        "active_sessions",
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "active_sessions",
        sa.Column(
            "refresh_token_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "active_sessions", sa.Column("is_active", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "active_sessions",
        sa.Column(
            "last_activity",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "active_sessions", sa.Column("device_info", sa.String(), nullable=True)
    )
    op.add_column(
        "active_sessions", sa.Column("ip_address", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_active_sessions_access_token_jti"),
        "active_sessions",
        ["access_token_jti"],
        unique=False,
    )
    op.create_index(
        op.f("ix_active_sessions_refresh_token_jti"),
        "active_sessions",
        ["refresh_token_jti"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_active_sessions_refresh_token_jti"), table_name="active_sessions"
    )
    op.drop_index(
        op.f("ix_active_sessions_access_token_jti"), table_name="active_sessions"
    )
    op.drop_column("active_sessions", "ip_address")
    op.drop_column("active_sessions", "device_info")
    op.drop_column("active_sessions", "last_activity")
    op.drop_column("active_sessions", "is_active")
    op.drop_column("active_sessions", "refresh_token_expires_at")
    op.drop_column("active_sessions", "access_token_expires_at")
    op.drop_column("active_sessions", "refresh_token_jti")
    op.drop_column("active_sessions", "access_token_jti")
    op.drop_index(op.f("ix_blacklisted_tokens_jti"), table_name="blacklisted_tokens")
    op.drop_index(op.f("ix_blacklisted_tokens_id"), table_name="blacklisted_tokens")
    op.drop_table("blacklisted_tokens")
    op.drop_index(op.f("ix_login_attempts_phone_number"), table_name="login_attempts")
    op.drop_index(op.f("ix_login_attempts_ip_address"), table_name="login_attempts")
    op.drop_index(op.f("ix_login_attempts_id"), table_name="login_attempts")
    op.drop_table("login_attempts")
    # ### end Alembic commands ###
